In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
b = np.array([[1],[2],[3],[4]])
print(b)

[[1]
 [2]
 [3]
 [4]]


In [19]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [20]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [24]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
d = np.array([100,100,100,100])
print(d)

[100 100 100 100]


In [26]:
c*d

array([[ 100,  200,  300,  400],
       [ 500,  600,  700,  800],
       [ 900, 1000, 1100, 1200]])

In [27]:
c.sum(axis=0)

array([15, 18, 21, 24])

In [28]:
c.sum(axis=1)

array([10, 26, 42])

In [29]:
p = np.array([1,2,3,4])
print(p)
q = np.array([[1,2,3,4]])
print(q)

[1 2 3 4]
[[1 2 3 4]]


In [31]:
print(p.shape)
print(q.shape)

(4,)
(1, 4)


In [36]:
assert(p.shape == (1,4))

AssertionError: 

In [37]:
assert(q.shape == (1,4))

In [38]:
x = np.random.randn(2,3)
y = np.random.randn(2,1)
z = x + y
print(z)
print(z.shape)

[[ 1.04268888 -0.35825864  0.20846188]
 [ 3.06585221  2.69285924  3.85412713]]
(2, 3)


In [39]:
x = np.random.randn(4,3)
y = np.random.randn(3,2)
z = x * y
print(z)
print(z.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [49]:
x = np.random.randn(12288,150)
y = np.random.randn(150,45)
print(np.dot(x,y).shape)


(12288, 45)


In [52]:
i = np.random.randn(3,3)
j = np.random.randn(3,1)
i*j

array([[-0.14179211,  0.13244379, -0.05407337],
       [ 0.96174293, -0.16144533,  1.54192396],
       [-0.41236192, -0.44193084, -0.051983  ]])